"""Renders docs/seed-data.md from the same dataset the seed uses (a test keeps the file in sync)."""

from __future__ import annotations

from pathlib import Path

from app.schemas.common import minor_to_decimal
from app.seed import data
from app.shops import SHOPS

DOC_PATH = Path(__file__).resolve().parent.parent.parent / "docs" / "seed-data.md"


def render_seed_markdown() -> str:
    out = [
        "# Seed data\n",
        "Generated by `python scripts/generate_seed_docs.py` from `app/seed/data.py` (do not edit by hand).\n",
        "All values are **synthetic demo data**: fictional manufacturers, demo prices (not real offers or exchange rates) and "
        "demo stock levels. `country_of_origin` is a validated ISO 3166-1 alpha-2 attribute of each product; it is a demo "
        "attribute, not a statement about any real product on the market. The origin is independent from the shop country "
        "and from the manufacturer name.\n",
        "Prices are gross (tax included) per sold pack. `minor` is the integer stored in the database.\n",
    ]
    for shop_id, shop in SHOPS.items():
        products = data.products_for(shop_id)
        origins = sorted({p.country_of_origin for p in products})
        out.append(f"\n## {shop.name} - `{shop_id}` (store country {shop.country}, {shop.currency}, schema `{shop.schema}`)\n")
        out.append(f"Catalog language: `{shop.locale}`. Origins used in this shop: {', '.join(origins)}. "
                   f"Orders are numbered `{shop.order_prefix}-<year>-<8 digits>`.\n")
        shipping = ", ".join(
            f"`{s['code']}` {minor_to_decimal(s['price_gross_minor'], shop.currency)} {shop.currency} ({s['price_gross_minor']} minor)"
            for s in data.shipping_for(shop_id)
        )
        out.append(f"Shipping methods: {shipping}.\n")
        out.append("| SKU | canonical_item_code | Name | Category | Pack | Price | minor | Stock | Status | Origin | Manufacturer |")
        out.append("| --- | --- | --- | --- | --- | ---: | ---: | ---: | --- | :---: | --- |")
        for p in products:
            if not p.active:
                status = "inactive (discontinued)"
            elif p.stock_quantity == 0:
                status = "out of stock"
            elif p.stock_quantity <= 5:
                status = "low stock"
            else:
                status = "in stock"
            price = f"{minor_to_decimal(p.unit_gross_minor, p.currency)} {p.currency}"
            out.append(
                f"| `{p.sku}` | `{p.canonical_item_code}` | {p.name} | {p.category_slug} | {p.units_per_pack} x {p.unit_label} | "
                f"{price} | {p.unit_gross_minor} | {p.stock_quantity} | {status} | {p.country_of_origin} | {p.manufacturer_name} |"
            )
    comp = [p for p in data.products_for("shop-pl") if p.compatible_with]
    out.append("\n## Consumable compatibility\n")
    for p in comp:
        out.append(f"- `{p.canonical_item_code}` is compatible only with: {', '.join(f'`{c}`' for c in p.compatible_with)}.")
    out.append(
        "\n## Fixtures used only by tests\n\n"
        "The test-suite inserts a product `PL-FIXTURE-RU-001` (origin `RU`) into the Polish shop to demonstrate that the "
        "seller's country never replaces the product origin (mixed `PL` + `RU` cart). It is **not** part of the normal seed.\n"
    )
    return "\n".join(out) + "\n"
