"""initial shop schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 14:51:37.420123
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=True),
    sa.Column('quote_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("result IN ('success', 'error')", name=op.f('ck_audit_events_result_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_customer_id_created_at', 'audit_events', ['customer_id', 'created_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('store_config',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name=op.f('ck_store_config_country_format')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_store_config_currency_format')),
    sa.CheckConstraint('id = 1', name=op.f('ck_store_config_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_config')),
    sa.UniqueConstraint('currency', name=op.f('uq_store_config_currency')),
    sa.UniqueConstraint('store_id', name=op.f('uq_store_config_store_id'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_api_keys_key_hash_sha256_hex')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_api_keys_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index('ix_api_keys_customer_id', 'api_keys', ['customer_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'checked_out')", name=op.f('ck_carts_status_valid')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_carts_version_positive')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_carts_currency_store_config')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_carts_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index('ix_carts_customer_id_status', 'carts', ['customer_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('canonical_item_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=120), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=False),
    sa.Column('unit_label', sa.String(length=32), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('unit_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('compatible_with', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_of_origin IN ('AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW')", name=op.f('ck_products_country_of_origin_iso')),
    sa.CheckConstraint('char_length(sku) BETWEEN 1 AND 64', name=op.f('ck_products_sku_length')),
    sa.CheckConstraint('stock_quantity >= 0', name=op.f('ck_products_stock_non_negative')),
    sa.CheckConstraint('unit_gross_minor >= 0', name=op.f('ck_products_price_non_negative')),
    sa.CheckConstraint('units_per_pack > 0', name=op.f('ck_products_units_per_pack_positive')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_products_version_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_products_currency_store_config')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_index('ix_products_canonical_item_code', 'products', ['canonical_item_code'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_country_of_origin', 'products', ['country_of_origin'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_gross_minor >= 0', name=op.f('ck_shipping_methods_price_non_negative')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_shipping_methods_currency_store_config')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_shipping_methods_code'))
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products')),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name=op.f('pk_cart_items'))
    )
    op.create_index('ix_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    op.create_table('checkout_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('cart_version', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipping_method_id', sa.Uuid(), nullable=False),
    sa.Column('shipping_method_code', sa.String(length=32), nullable=False),
    sa.Column('shipping_method_name', sa.String(length=120), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('shipping_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('origin_countries', sa.ARRAY(sa.String(length=2)), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_checkout_quotes_expiry_after_creation')),
    sa.CheckConstraint('subtotal_gross_minor >= 0 AND shipping_gross_minor >= 0', name=op.f('ck_checkout_quotes_amounts_non_negative')),
    sa.CheckConstraint('total_gross_minor = subtotal_gross_minor + shipping_gross_minor', name=op.f('ck_checkout_quotes_total_consistent')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_checkout_quotes_cart_id_carts')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_checkout_quotes_currency_store_config')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_checkout_quotes_customer_id_customers')),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_methods.id'], name=op.f('fk_checkout_quotes_shipping_method_id_shipping_methods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_quotes'))
    )
    op.create_index('ix_checkout_quotes_cart_id', 'checkout_quotes', ['cart_id'], unique=False)
    op.create_index('ix_checkout_quotes_customer_id', 'checkout_quotes', ['customer_id'], unique=False)
    op.create_table('checkout_quote_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('canonical_item_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=120), nullable=False),
    sa.Column('unit_label', sa.String(length=32), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('line_total_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('product_version', sa.Integer(), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=False),
    sa.CheckConstraint("country_of_origin IN ('AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW')", name=op.f('ck_checkout_quote_items_country_of_origin_iso')),
    sa.CheckConstraint('line_total_gross_minor = unit_gross_minor * quantity', name=op.f('ck_checkout_quote_items_line_total_consistent')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_checkout_quote_items_quantity_positive')),
    sa.CheckConstraint('unit_gross_minor >= 0', name=op.f('ck_checkout_quote_items_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_checkout_quote_items_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['checkout_quotes.id'], name=op.f('fk_checkout_quote_items_quote_id_checkout_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_quote_items')),
    sa.UniqueConstraint('quote_id', 'line_no', name=op.f('uq_checkout_quote_items_quote_id_line_no')),
    sa.UniqueConstraint('quote_id', 'product_id', name=op.f('uq_checkout_quote_items_quote_id_product_id'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('shipping_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('shipping_method_code', sa.String(length=32), nullable=False),
    sa.Column('shipping_method_name', sa.String(length=120), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin_countries', sa.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_status IN ('paid_mock')", name=op.f('ck_orders_payment_status_valid')),
    sa.CheckConstraint("status IN ('placed')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('total_gross_minor = subtotal_gross_minor + shipping_gross_minor', name=op.f('ck_orders_total_consistent')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_orders_cart_id_carts')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_orders_currency_store_config')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['quote_id'], ['checkout_quotes.id'], name=op.f('fk_orders_quote_id_checkout_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('cart_id', name=op.f('uq_orders_cart_id')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number')),
    sa.UniqueConstraint('quote_id', name=op.f('uq_orders_quote_id'))
    )
    op.create_index('ix_orders_customer_id_created_at', 'orders', ['customer_id', 'created_at'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(idempotency_key) BETWEEN 8 AND 128', name=op.f('ck_idempotency_records_key_length')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_idempotency_records_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_idempotency_records_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('customer_id', 'operation', 'idempotency_key', name=op.f('uq_idempotency_records_customer_id_operation_idempotency_key'))
    )
    op.create_table('mock_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=False),
    sa.Column('amount_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('succeeded')", name=op.f('ck_mock_payments_status_valid')),
    sa.CheckConstraint('amount_gross_minor >= 0', name=op.f('ck_mock_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['currency'], ['store_config.currency'], name=op.f('fk_mock_payments_currency_store_config')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_mock_payments_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_mock_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_payments')),
    sa.UniqueConstraint('order_id', name=op.f('uq_mock_payments_order_id'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('canonical_item_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=120), nullable=False),
    sa.Column('unit_label', sa.String(length=32), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('line_total_gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('product_version', sa.Integer(), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=False),
    sa.CheckConstraint("country_of_origin IN ('AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW')", name=op.f('ck_order_items_country_of_origin_iso')),
    sa.CheckConstraint('line_total_gross_minor = unit_gross_minor * quantity', name=op.f('ck_order_items_line_total_consistent')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'line_no', name=op.f('uq_order_items_order_id_line_no'))
    )
    # ### end Alembic commands ###

    # Hand-written part -----------------------------------------------------------------
    # The objects below are created in the schema selected by search_path (see migrations/env.py).
    op.execute(sa.schema.CreateSequence(sa.Sequence("order_number_seq", start=1)))

    # `products.version` is bumped by the database whenever a quote-relevant attribute changes
    # (price, origin, packaging, identity, active flag). Stock changes do NOT bump it, so a
    # purchase by someone else does not make every other quote stale.
    op.execute(
        """
        CREATE FUNCTION products_bump_version() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.sku, NEW.canonical_item_code, NEW.name, NEW.manufacturer_name,
                NEW.country_of_origin, NEW.unit_label, NEW.units_per_pack,
                NEW.unit_gross_minor, NEW.currency, NEW.active)
               IS DISTINCT FROM
               (OLD.sku, OLD.canonical_item_code, OLD.name, OLD.manufacturer_name,
                OLD.country_of_origin, OLD.unit_label, OLD.units_per_pack,
                OLD.unit_gross_minor, OLD.currency, OLD.active)
            THEN
                NEW.version := OLD.version + 1;
            ELSE
                NEW.version := OLD.version;
            END IF;
            NEW.created_at := OLD.created_at;
            NEW.updated_at := now();
            RETURN NEW;
        END
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER trg_products_bump_version BEFORE UPDATE ON products "
        "FOR EACH ROW EXECUTE FUNCTION products_bump_version()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_products_bump_version ON products")
    op.execute("DROP FUNCTION IF EXISTS products_bump_version()")
    op.execute(sa.schema.DropSequence(sa.Sequence("order_number_seq")))
    op.drop_table('order_items')
    op.drop_table('mock_payments')
    op.drop_table('idempotency_records')
    op.drop_index('ix_orders_customer_id_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('checkout_quote_items')
    op.drop_index('ix_checkout_quotes_customer_id', table_name='checkout_quotes')
    op.drop_index('ix_checkout_quotes_cart_id', table_name='checkout_quotes')
    op.drop_table('checkout_quotes')
    op.drop_index('ix_cart_items_product_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_table('shipping_methods')
    op.drop_index('ix_products_country_of_origin', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_canonical_item_code', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_carts_customer_id_status', table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_api_keys_customer_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('store_config')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_index('ix_audit_events_customer_id_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
